/**
 * Offline access to the normalized HyperFrames capability catalog.
 *
 * The index is generated by scripts/syncCapabilityIndex.ts from a pinned
 * upstream registry commit plus the vendored blueprint/rule/frame catalogs.
 * Authoring never reaches the network.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

export type CapabilityKind =
  | "registry-block"
  | "registry-component"
  | "blueprint"
  | "motion-rule"
  | "frame-preset";

export interface CapabilityRecord {
  id: string;
  kind: CapabilityKind;
  title: string;
  description: string;
  tags: string[];
  reuseTier: "parameter-swap" | "safe-composition" | "custom-build";
  durationSec?: number;
  dimensions?: { width: number; height: number };
  configurableVariables?: string[];
  dependencies?: string[];
  files?: string[];
  preview?: { poster?: string; video?: string };
  provenance: {
    source: string;
    ref: string;
  };
}

export interface CapabilityIndex {
  version: 1;
  registry: {
    commit: string;
    version: string;
    runtimeVersion: string;
    itemCount: number;
  };
  capabilities: CapabilityRecord[];
}

const INDEX_PATH = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../../capabilities/capability-index.json",
);

let cached: CapabilityIndex | undefined;

export function loadCapabilityIndex(): CapabilityIndex {
  if (cached) return cached;
  if (!fs.existsSync(INDEX_PATH)) {
    throw new Error(
      "missing synced capability index; run npm run capabilities:sync -w @sequences/slack",
    );
  }
  const value = JSON.parse(fs.readFileSync(INDEX_PATH, "utf8")) as CapabilityIndex;
  if (value.version !== 1 || !Array.isArray(value.capabilities)) {
    throw new Error("capability-index.json has an unsupported shape");
  }
  cached = value;
  return value;
}

function words(value: string): Set<string> {
  const result = new Set(
    value
      .toLowerCase()
      .replace(/[^a-z0-9%]+/g, " ")
      .split(/\s+/)
      .filter((word) => word.length >= 2),
  );
  if ([...result].some((word) => /^(stat|stats|metric|percent|growth|number|count|%)$/.test(word))) {
    for (const word of ["data", "chart", "statistics", "count"]) result.add(word);
  }
  if ([...result].some((word) => /^(code|developer|cli|terminal|api)$/.test(word))) {
    for (const word of ["code", "developer", "terminal"]) result.add(word);
  }
  return result;
}

function scoreCapability(capability: CapabilityRecord, queryWords: Set<string>): number {
  const idWords = words(capability.id);
  const titleWords = words(capability.title);
  const descriptionWords = words(capability.description);
  const tagWords = new Set(capability.tags.flatMap((tag) => [...words(tag)]));
  let score = 0;
  for (const word of queryWords) {
    if (idWords.has(word)) score += 9;
    if (tagWords.has(word)) score += 7;
    if (titleWords.has(word)) score += 5;
    if (descriptionWords.has(word)) score += 2;
  }
  if (
    score > 0 &&
    (capability.kind === "registry-block" || capability.kind === "registry-component")
  ) {
    score += 8;
  }
  return score;
}

const CREATIVE_DEFAULTS = [
  "grain-overlay",
  "shimmer-sweep",
  "ui-3d-reveal",
  "logo-outro",
];

export function selectCapabilities(
  query: string,
  limit = 8,
): { index: CapabilityIndex; selected: CapabilityRecord[] } {
  const index = loadCapabilityIndex();
  const queryWords = words(query);
  const ranked = index.capabilities
    .map((capability) => ({ capability, score: scoreCapability(capability, queryWords) }))
    .filter((item) => item.score > 0)
    .sort((a, b) => b.score - a.score || a.capability.id.localeCompare(b.capability.id))
    .map((item) => item.capability);

  const byId = new Map(index.capabilities.map((capability) => [capability.id, capability]));
  const defaults = CREATIVE_DEFAULTS
    .map((id) => byId.get(id))
    .filter((item): item is CapabilityRecord => Boolean(item));
  const selected = [...new Map(
    [...ranked, ...defaults].map((capability) => [capability.id, capability]),
  ).values()].slice(0, limit);
  return { index, selected };
}

function compactCatalog(index: CapabilityIndex): string {
  const groups = new Map<CapabilityKind, string[]>();
  for (const capability of index.capabilities) {
    const current = groups.get(capability.kind) ?? [];
    current.push(capability.id);
    groups.set(capability.kind, current);
  }
  return [...groups.entries()]
    .map(([kind, ids]) => `- ${kind} (${ids.length}): ${ids.sort().join(", ")}`)
    .join("\n");
}

function selectedDetail(capability: CapabilityRecord): string {
  const traits = [
    capability.durationSec ? `${capability.durationSec}s` : "",
    capability.dimensions
      ? `${capability.dimensions.width}x${capability.dimensions.height}`
      : "",
    capability.configurableVariables?.length
      ? `variables: ${capability.configurableVariables.join(", ")}`
      : "",
    `reuse: ${capability.reuseTier}`,
  ].filter(Boolean).join(" · ");
  return `- **${capability.id}** [${capability.kind}; ${traits}]: ${capability.description}${
    capability.tags.length ? ` Tags: ${capability.tags.join(", ")}.` : ""
  }`;
}

export function renderCapabilityContext(query: string): {
  text: string;
  capabilityIds: string[];
  registryVersion: string;
} {
  const { index, selected } = selectCapabilities(query);
  return {
    capabilityIds: selected.map((capability) => capability.id),
    registryVersion: index.registry.commit,
    text: [
      "## Synced HyperFrames capability index (offline, registry-backed)",
      `Catalog: ${index.capabilities.length} normalized capabilities from registry ${index.registry.version}`,
      `at ${index.registry.commit.slice(0, 12)}; production runtime remains pinned to ${index.registry.runtimeVersion}.`,
      "Reuse outranks invention when a listed capability fits. Treat registry items as",
      "known-good visual structures and vocabulary. The index is metadata, not permission",
      "to fetch at render time: emit one standalone composition and use only project-local assets.",
      "",
      "### Complete catalog",
      compactCatalog(index),
      "",
      "### Best matches for this job",
      ...selected.map(selectedDetail),
      "",
      "Capability choices guide the storyboard; they are not a quota. Combine them,",
      "use structure only, or build custom when the visual thesis genuinely needs it.",
    ].join("\n"),
  };
}
